server:
  port: 9000

spring:
#  datasource:
#    url: jdbc:mysql://192.168.23.200:3306/bbs_base?characterEncoding=utf-8
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: ZXL=root1

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.sy.patient.controller
  mapper-locations: mappers/*.xml